const all_bird_names = new Set([

  "'ula",
  "\u014di",
  "african collared dove",
  "african ring-necked dove",
  "akiaki",
  "albatross",
  "allied shearwater",
  "american whimbrel",
  "amokura",
  "angel tern",
  "antarctic fulmar",
  "antarctic prion",
  "antarctic skua",
  "antarctic tern",
  "antipodean albatross",
  "antipodes island parakeet",
  "antipodes parakeet",
  "antipodes red-crowned parakeet",
  "arctic skua",
  "arctic tern",
  "asiatic golden plover",
  "asiatic whimbrel",
  "auckland island flightless duck",
  "auckland island rail",
  "auckland island shag",
  "auckland island snipe",
  "auckland island teal",
  "auckland teal",
  "australasian bittern",
  "australasian crested grebe",
  "australasian gannet",
  "australasian harrier",
  "australasian pied stilt",
  "australasian shoveler",
  "australasian swamphen",
  "australian brown quail",
  "australian coot",
  "australian gannet",
  "australian magpie",
  "baillon's crake",
  "banded dotterel",
  "banded rail",
  "bar tailed godwit",
  "bar-tailed godwit",
  "barbary dove",
  "bartailed godwit",
  "barwit",
  "bell bird",
  "bellbird",
  "bittern",
  "black backed gull",
  "black bellied storm petrel",
  "black billed gull",
  "black browed albatross",
  "black browed mollymawk",
  "black burrower",
  "black cormorant",
  "black duck",
  "black fantail",
  "black fronted dotterel",
  "black fronted tern",
  "black noddy",
  "black oystercatcher",
  "black petrel",
  "black robin",
  "black shag",
  "black stilt",
  "black swan",
  "black teal",
  "black tit",
  "black tomtit",
  "black winged petrel",
  "black-backed gull",
  "black-backed magpie",
  "black-bellied storm petrel",
  "black-billed gull",
  "black-billed spoonbill",
  "black-billed tern",
  "black-capped petrel",
  "black-fronted dotterel",
  "black-fronted plover",
  "black-fronted tern",
  "black-tailed petrel",
  "black-tailed shearwater",
  "black-winged petrel",
  "black-winged stilt",
  "blackbacked gull",
  "blackbellied storm petrel",
  "blackbilled gull",
  "blackbird",
  "blackbrowed albatross",
  "blackbrowed mollymawk",
  "blackfronted dotterel",
  "blackfronted tern",
  "blackwinged petrel",
  "blight-bird",
  "blue billy",
  "blue crane",
  "blue duck",
  "blue heron",
  "blue mountain duck",
  "blue penguin",
  "blue petrel",
  "blue shag (southern subspecies)",
  "blue-billy",
  "blue-faced booby",
  "blue-footed petrel",
  "blue-gray noddy",
  "blue-grey noddy",
  "blue-wattled crow",
  "boobook",
  "boomer",
  "bosun bird",
  "bounty cormorant",
  "bounty island cormorant",
  "bounty island mollymawk",
  "bounty island shag",
  "bounty mollymawk",
  "bounty shag",
  "broad billed prion",
  "broad-billed prion",
  "broad-tailed storm petrel",
  "broadbilled prion",
  "bronze shag",
  "brown bittern",
  "brown creeper",
  "brown duck",
  "brown kiwi",
  "brown parrot",
  "brown petrel",
  "brown quail",
  "brown skua",
  "brown teal",
  "brown-beaked shearwater",
  "buff-banded rail",
  "buller's albatross",
  "buller's gull",
  "buller's mollymawk",
  "buller's shearwater",
  "bullers albatross",
  "bullers mollymawk",
  "bullers shearwater",
  "bush canary",
  "bush falcon",
  "bush hawk",
  "bush parrot",
  "bush robin",
  "caledonian petrel",
  "california quail",
  "campbell albatross",
  "campbell black-browed albatross",
  "campbell black-browed mollymawk",
  "campbell cormorant",
  "campbell flightless teal",
  "campbell island albatross",
  "campbell island cormorant",
  "campbell island flightless teal",
  "campbell island mollymawk",
  "campbell island shag",
  "campbell island teal",
  "campbell mollymawk",
  "campbell shag",
  "campbell teal",
  "canada goose",
  "cape barren goose",
  "cape hen",
  "cape petrel",
  "cape pigeon",
  "carunculated shag",
  "caspian tern",
  "cattle egret",
  "chaffinch",
  "chatham albatross",
  "chatham gerygone",
  "chatham island albatross",
  "chatham island black robin",
  "chatham island cormorant",
  "chatham island mollymawk",
  "chatham island oystercatcher",
  "chatham island petrel",
  "chatham island pigeon",
  "chatham island robin",
  "chatham island shag",
  "chatham island snipe",
  "chatham island taiko",
  "chatham island warbler",
  "chatham island yellow-crowned parakeet",
  "chatham mollymawk",
  "chatham petrel",
  "chatham shag",
  "chinese dove",
  "chinese pheasant",
  "chukar partridge",
  "chukar",
  "chukor partridge",
  "chukor",
  "cinereous wattlebird",
  "cirl bunting",
  "common blackbird",
  "common chaffinch",
  "common coot",
  "common diving petrel",
  "common myna",
  "common pheasant",
  "common redpoll",
  "common skylark",
  "common starling",
  "cook strait cormorant",
  "cook's petrel",
  "cooks petrel",
  "coot",
  "cormorant",
  "creeper",
  "crested grebe",
  "crested penguin",
  "crimson parrot",
  "crimson rosella",
  "crook-bill",
  "crow",
  "crowned guineafowl",
  "crozet island prion",
  "crozet prion",
  "dabchick",
  "dawson's petrel",
  "diver",
  "diving petrel",
  "domestic goose",
  "domestic pigeon",
  "dominican gull",
  "dotterel",
  "double-banded plover",
  "dove petrel",
  "dove prion",
  "dunnock",
  "eastern falcon",
  "eastern golden plover",
  "eastern great egret",
  "eastern reef egret",
  "eastern rockhopper penguin",
  "eastern rosella",
  "eastern turnstone",
  "egg bird",
  "english pheasant",
  "english sparrow",
  "erect crested penguin",
  "erect-crested penguin",
  "erectcrested penguin",
  "eurasian blackbird",
  "eurasian coot",
  "eurasian skylark",
  "european goldfinch",
  "european greenfinch",
  "european starling",
  "fairy penguin",
  "fairy prion",
  "fairy tern",
  "falcon",
  "fantail",
  "feral goose",
  "feral pigeon",
  "feral turkey",
  "fernbird",
  "finsch's oystercatcher",
  "fiordland crested penguin",
  "fiordland penguin",
  "flesh footed shearwater",
  "flesh-footed shearwater",
  "fleshfooted shearwater",
  "flightless duck",
  "flightless teal",
  "flutterer",
  "fluttering shearwater",
  "forbe's parakeet",
  "forbes parakeet",
  "forbes' parakeet",
  "forbes's parakeet",
  "forster's shearwater",
  "foveaux shag",
  "frigate petrel",
  "fulmar prion",
  "fulmar",
  "galah",
  "gannet",
  "georgian diving petrel",
  "german owl",
  "gerygone",
  "giant fulmar",
  "giant petrel",
  "gibson's albatross",
  "glutton",
  "goldfinch",
  "gould's petrel",
  "goulds petrel",
  "gray duck",
  "gray noddy",
  "gray petrel",
  "gray teal",
  "gray ternlet",
  "gray warbler",
  "gray-backed storm petrel",
  "gray-faced petrel",
  "gray\u2019s shag",
  "graylag goose",
  "great cormorant",
  "great crested grebe",
  "great egret",
  "great skua",
  "great spotted kiwi",
  "great white egret",
  "great white heron",
  "great-winged petrel",
  "grebe",
  "green finch",
  "green linnet",
  "green parakeet",
  "greenfinch",
  "greenhead",
  "greenie",
  "grey backed storm petrel",
  "grey duck",
  "grey faced petrel",
  "grey fantail",
  "grey gerygone",
  "grey headed albatross",
  "grey headed mollymawk",
  "grey noddy",
  "grey petrel",
  "grey teal",
  "grey ternlet",
  "grey warbler",
  "grey-backed mollymawk",
  "grey-backed shearwater",
  "grey-backed storm petrel",
  "grey-faced petrel",
  "grey-headed albatross",
  "grey-headed mollymawk",
  "greybacked storm petrel",
  "greyfaced petrel",
  "greyheaded albatross",
  "greyheaded mollymawk",
  "greylag goose",
  "h\u0101koakoa",
  "hakoakoa",
  "hakoko",
  "harrier hawk",
  "harrier",
  "hawk",
  "hedge accentor",
  "hedge sparrow",
  "helmeted guineafowl",
  "hihi",
  "hoiho",
  "hoihoi",
  "hokako",
  "homing pigeon",
  "honga",
  "honge",
  "honker",
  "house sparrow",
  "house swallow",
  "huahou",
  "hutton's shearwater",
  "huttons shearwater",
  "indian myna",
  "indian peafowl",
  "j c bird",
  "jackbird",
  "jackie (chathams)",
  "jesus christ bird",
  "k\u0101hu",
  "k\u0101k\u0101",
  "k\u0101k\u0101po",
  "k\u0101k\u0101riki karaka",
  "k\u0101k\u0101riki",
  "k\u0101mana",
  "k\u0101rearea",
  "k\u0101ruhiruhi",
  "k\u014dk\u014d",
  "k\u014dka",
  "k\u014dkako",
  "k\u014dtare",
  "k\u014dtuku ngutupapa",
  "k\u014dtuku",
  "kahawai bird",
  "kahu",
  "kaireka",
  "kak\u012b",
  "kak\u012b\u0101nau",
  "kaka",
  "kaka-wairiki",
  "kakapo",
  "kakariki karaka",
  "kakariki",
  "kakariwai",
  "kakaruai",
  "kakaruia",
  "kakaruwai",
  "kaki",
  "kakianau",
  "kamana",
  "karearea",
  "karoro",
  "karuhiruhi",
  "kata tei",
  "kawariki",
  "kawau paka",
  "kawau t\u016b\u012b",
  "kawau tikitiki",
  "kawau tui",
  "kawau",
  "kawkaw",
  "kea",
  "kelp gull",
  "kerer\u016b",
  "kereru",
  "kerguelen petrel",
  "kermadec petrel",
  "kermadec storm petrel",
  "king cormorant",
  "king shag",
  "kingfisher",
  "kiwi pukupuku",
  "knot",
  "ko'ae",
  "koekoe\u0101",
  "koekoea",
  "koera",
  "kohoperoa",
  "koitareke",
  "koka",
  "kokako",
  "koko",
  "kokopa",
  "konini",
  "kookaburra",
  "koputu",
  "korimako",
  "koro\u0101tito",
  "koroatito",
  "koror\u0101",
  "korora",
  "korure",
  "kotare",
  "kotoreke",
  "kotuku ngutupapa",
  "kotuku",
  "kuaka",
  "kuera",
  "kuia",
  "kuihi",
  "kuku",
  "kukupa",
  "kuruwhengi",
  "laceneck dove",
  "large black shag",
  "large pied shag",
  "laughing kookaburra",
  "laughing-jackass",
  "least golden plover",
  "lesser broad-billed prion",
  "lesser golden plover",
  "lesser knot",
  "light mantled sooty albatross",
  "light-mantled albatross",
  "light-mantled sooty albatross",
  "lightmantled sooty albatross",
  "little black cormorant",
  "little black shag",
  "little blue penguin",
  "little cormorant",
  "little owl",
  "little penguin",
  "little pied cormorant",
  "little pied shag",
  "little shag",
  "little shearwater",
  "little spotted kiwi",
  "little tern",
  "long tailed cuckoo",
  "long tailed skua",
  "long-tailed cuckoo",
  "long-tailed jaeger",
  "long-tailed koel",
  "long-tailed skua",
  "longtailed cuckoo",
  "longtailed skua",
  "love tern",
  "m\u0101t\u0101t\u0101",
  "m\u0101tuitui",
  "mackerel gull",
  "macquarie cormorant",
  "macquarie island cormorant",
  "macquarie island shag",
  "macquarie shag",
  "magenta petrel",
  "magpie",
  "makipae",
  "makipai",
  "makomako",
  "malay spotted dove",
  "malherbe's parakeet",
  "mallard duck",
  "mallard",
  "manu pango",
  "marlborough sounds shag",
  "marsh crake",
  "masked booby",
  "masked gannet",
  "masked lapwing",
  "masked plover",
  "matapouri",
  "matata",
  "matuitui",
  "matuku moana",
  "matuku",
  "matuku-h\u016brepo",
  "matuku-hurepo",
  "maui-potiki",
  "mccormick's skua",
  "mcpherson quail",
  "medium-billed prion",
  "mioweka",
  "miromiro",
  "mockie",
  "moho perer\u016b",
  "mohoua",
  "mohua",
  "mollyhawk",
  "mollymawk",
  "morepork",
  "mother carey's chicken",
  "mottled petrel",
  "mountain duck",
  "mountain lowry",
  "mountain parrot",
  "mourningbird",
  "mute swan",
  "mutton bird",
  "muttonbird",
  "myna",
  "mynah",
  "narrow billed prion",
  "narrow-billed prion",
  "narrowbilled prion",
  "native pigeon",
  "nelly",
  "new caledonian petrel",
  "new zealand bellbird",
  "new zealand creeper",
  "new zealand crested penguin",
  "new zealand dabchick",
  "new zealand dotterel",
  "new zealand falcon",
  "new zealand fantail",
  "new zealand gerygone",
  "new zealand grebe",
  "new zealand king cormorant",
  "new zealand king shag",
  "new zealand kingfisher",
  "new zealand mountain parrot",
  "new zealand muttonbird",
  "new zealand owl",
  "new zealand pied oystercatcher",
  "new zealand pigeon",
  "new zealand pipit",
  "new zealand plover",
  "new zealand robin",
  "new zealand rock wren",
  "new zealand scaup",
  "new zealand shearwater",
  "new zealand shore plover",
  "new zealand shoveler",
  "new zealand snipe (collective name for several forms now recognised as full species)",
  "new zealand snipe (collective name for several forms now recognised as full species)",
  "new zealand storm petrel",
  "new zealand titmouse",
  "new zealand tomtit",
  "ngirungiru",
  "ngutu pare",
  "ngutuparore",
  "night parrot",
  "north island brown kiwi",
  "north island kokako",
  "north island robin",
  "north island saddleback",
  "northern giant petrel",
  "northern mallard",
  "northern mutton bird",
  "northern muttonbird",
  "northern royal albatross",
  "notornis",
  "oi",
  "okarito brown kiwi",
  "onga",
  "onge",
  "orange fronted parakeet",
  "orange-fronted parakeet",
  "orange-wattled crow",
  "orangefronted parakeet",
  "otago shag",
  "owl",
  "owl-parrot",
  "oystercatcher",
  "p\u0101ngurunguru",
  "p\u0101pango",
  "p\u0101rera",
  "p\u0101teke",
  "p\u012bhoihoi",
  "p\u012bp\u012bwharauroa",
  "p\u012bpipi",
  "p\u012bwakawaka",
  "p\u012bwauwau",
  "p\u014dpokatea",
  "p\u014dpokotea",
  "p\u016bkeko",
  "p\u016btangitangi",
  "p\u016bteketeke",
  "p\u016bweto",
  "pacific albatross",
  "pacific black duck",
  "pacific gannet",
  "pacific golden plover",
  "pacific mollymawk",
  "pahirini",
  "pakah\u0101",
  "pakaha",
  "pakara",
  "pale-footed shearwater",
  "pangurunguru",
  "papango",
  "paradise duck",
  "paradise shelduck",
  "parar\u0101",
  "parara",
  "parasitic jaeger (jaeger is german for hunter)",
  "parea",
  "parekareka",
  "parera",
  "pari",
  "parkinson's petrel",
  "parrie",
  "parry",
  "parson bird",
  "pateke",
  "peacock",
  "peafowl",
  "peahen",
  "peale's petrel",
  "pearl-necked dove",
  "pediunker",
  "peihana",
  "petrel",
  "pheasant",
  "pied cormorant",
  "pied fantail",
  "pied oystercatcher",
  "pied shag",
  "pied stilt",
  "pied tit",
  "pied tomtit",
  "pig goose",
  "pigeon",
  "pihoihoi",
  "pintado petrel",
  "pipipi",
  "pipit",
  "pipiwharauroa",
  "piropiro",
  "pitt cormorant",
  "pitt island cormorant",
  "pitt island shag",
  "pitt shag",
  "piwakawaka",
  "piwauwau",
  "plover",
  "plumed quail",
  "poaka",
  "pohowera",
  "pokotiwha",
  "polar skua",
  "pomarine jaeger",
  "pomarine skua",
  "pook",
  "popokatea",
  "popokotea",
  "porete",
  "powhaitere",
  "pukeko",
  "purple gallinule",
  "purple swamphen",
  "putangitangi",
  "puteketeke",
  "putoto",
  "puweto",
  "pycroft's petrel",
  "pycrofts petrel",
  "quail hawk",
  "quail",
  "racing pigeon",
  "rail",
  "rainbird",
  "raipo",
  "rako",
  "ranguru",
  "red billed gull",
  "red crowned parakeet",
  "red knot",
  "red lowry",
  "red necked stint",
  "red parrot",
  "red tailed tropicbird",
  "red-billed gull",
  "red-breasted dotterel",
  "red-crowned parakeet",
  "red-headed parakeet",
  "red-necked stint",
  "red-tailed tropicbird",
  "redbilled gull",
  "redcrowned parakeet",
  "rednecked stint",
  "redpoll",
  "redtailed tropicbird",
  "reef heron",
  "reischek's parakeet",
  "reischeks parakeet",
  "reoreo",
  "richard's pipit",
  "richdale's diving petrel",
  "richdale's penguin",
  "rifleman",
  "ring dove",
  "ring-necked pheasant",
  "ringed turtle dove",
  "riroriro",
  "roa",
  "robin",
  "rock dove",
  "rock pigeon",
  "rock wren",
  "rook",
  "roroa",
  "rose cockatoo",
  "rose-breasted cockatoo",
  "roseate cockatoo",
  "rough-faced shag",
  "rowi",
  "royal albatross",
  "royal spoonbill",
  "ruddy turnstone",
  "rufous-necked stint",
  "ruru",
  "sacred kingfisher",
  "saddleback",
  "salvin's albatross",
  "salvin's mollymawk",
  "salvin's prion",
  "salvins albatross",
  "salvins mollymawk",
  "salvins prion",
  "sand plover",
  "scaup",
  "sea vulture",
  "sea-swallow",
  "seagull",
  "shag",
  "sharp tailed sandpiper",
  "sharp-tailed sandpiper",
  "sharptailed sandpiper",
  "shearwater",
  "shining bronze-cuckoo",
  "shining cuckoo",
  "shoemaker",
  "shore dotterel",
  "shore plover",
  "short tailed shearwater",
  "short-tailed shearwater",
  "shorttailed shearwater",
  "shoveler",
  "shoveller",
  "shy albatross",
  "shy mollymawk",
  "silver gull",
  "silver-eye",
  "silver-grey fulmar",
  "silvereye",
  "sipo",
  "skua",
  "skylark",
  "slender billed prion",
  "slender-billed fulmar",
  "slender-billed prion",
  "slenderbilled prion",
  "snares crested penguin",
  "snares island penguin",
  "snares island snipe",
  "snares penguin",
  "snares snipe",
  "snipe (collective name for several forms now recognised as full species)",
  "snipe",
  "snow petrel",
  "snowy albatross",
  "soft plumaged petrel",
  "soft-plumaged petrel",
  "softplumaged petrel",
  "song thrush",
  "sooty rail",
  "sooty shearwater",
  "sooty tern",
  "sooty-capped petrel",
  "south georgian diving petrel",
  "south island kokako",
  "south island pied oystercatcher",
  "south island robin",
  "south island saddleback",
  "south island takahe",
  "south island wren",
  "south polar skua",
  "south-west pacific swamphen",
  "southern black-backed gull",
  "southern brown kiwi",
  "southern crested grebe",
  "southern falcon",
  "southern fulmar",
  "southern giant petrel",
  "southern great skua",
  "southern royal albatross",
  "southern skua",
  "sparrow hawk",
  "spoonbill",
  "spoonie",
  "spoony",
  "spotless crake",
  "spotted dove",
  "spotted shag",
  "spotted turtle-dove",
  "spur winged plover",
  "spur-wing",
  "spur-winged plover",
  "spurwinged plover",
  "starling",
  "stewart cormorant",
  "stewart island cormorant",
  "stewart island shag",
  "stewart shag",
  "stinker",
  "stinkpot",
  "stitchbird",
  "storm petrel",
  "street pigeon",
  "subantarctic little shearwater",
  "subantarctic skua",
  "subantarctic snipe",
  "sulphur crested cockatoo",
  "sulphur-crested cockatoo",
  "sulphurcrested cockatoo",
  "sunday island petrel",
  "swallowtail",
  "swamp harrier",
  "swamphen",
  "t\u0101iko",
  "t\u0101kapu",
  "t\u0101koketai",
  "t\u0101kupu",
  "t\u0113t\u0113 moroiti",
  "t\u0113t\u0113",
  "t\u012beke",
  "t\u012brairaka",
  "t\u012bt\u012b wainui",
  "t\u012bt\u012b",
  "t\u012btitipounamu",
  "t\u014drea pango",
  "t\u014drea tai",
  "t\u014drea",
  "t\u016b\u012b",
  "t\u016bturiwhatu",
  "t\u016bturuatu",
  "taihoropi (hokianga)",
  "taiko",
  "takah\u0113",
  "takahe",
  "takahikare",
  "takahikare-moana",
  "takapu",
  "takupu",
  "tar\u0101puka",
  "tar\u0101punga",
  "tara iti",
  "tara",
  "taranui",
  "tarapiroe",
  "tarapirohe",
  "tarapo",
  "tarapuka",
  "tarapunga",
  "taratimoho (waikato)",
  "tarepo",
  "tasman booby",
  "tasmanian mutton bird",
  "tasmanian muttonbird",
  "tauhou",
  "tawake",
  "tawaki",
  "tchaik",
  "teal",
  "teetotum",
  "tete moroiti",
  "tete",
  "thick-billed penguin",
  "thin billed prion",
  "thin-billed prion",
  "thinbilled prion",
  "thrush",
  "tiaki",
  "tieke",
  "tirairaka",
  "titi wainui",
  "titi",
  "titiporangi",
  "titipounamu",
  "titmouse",
  "tiu",
  "toanui",
  "tokoeka",
  "tomtit",
  "torea pango",
  "torea tai",
  "torea",
  "toroa pango",
  "toroa",
  "toroa-a-ruru",
  "totokipio",
  "totorore",
  "toutouwai",
  "tuanui",
  "tufted guineafowl",
  "tui",
  "tuke",
  "turnstone",
  "tutukiwi",
  "tuturiwhatu",
  "tuturiwhatu-pukunui",
  "tuturuatu",
  "uniform parakeet",
  "utick",
  "variable oystercatcher",
  "victoria penguin",
  "vieillot\u2019s storm petrel",
  "voc",
  "wandering albatross",
  "warbler",
  "warou",
  "wax-eye",
  "waxeye",
  "wedge tailed shearwater",
  "wedge-tailed mutton bird",
  "wedge-tailed muttonbird",
  "wedge-tailed shearwater",
  "wedgetailed shearwater",
  "weka",
  "welcome swallow",
  "werewere",
  "westland black petrel",
  "westland petrel",
  "weweia",
  "whale bird",
  "whalebird",
  "whimbrel",
  "whio",
  "whistling booby",
  "white bellied storm petrel",
  "white booby",
  "white capped albatross",
  "white capped mollymawk",
  "white chinned petrel",
  "white cockatoo",
  "white faced heron",
  "white faced storm petrel",
  "white fronted tern",
  "white headed petrel",
  "white heron",
  "white naped petrel",
  "white noddy",
  "white swan",
  "white tern",
  "white winged black tern",
  "white-backed magpie",
  "white-bellied storm petrel",
  "white-capped albatross",
  "white-capped mollymawk",
  "white-capped noddy",
  "white-cheeked rosella",
  "white-chinned petrel",
  "white-eye",
  "white-faced heron",
  "white-faced storm petrel",
  "white-flippered penguin",
  "white-fronted tern",
  "white-headed petrel",
  "white-headed stilt",
  "white-naped petrel",
  "white-necked petrel",
  "white-throated petrel",
  "white-throated shag",
  "white-winged black tern",
  "white-winged fulmar",
  "white-winged petrel",
  "white-winged tern",
  "whitebellied storm petrel",
  "whitecapped albatross",
  "whitecapped mollymawk",
  "whitechinned petrel",
  "whitefaced heron",
  "whitefaced storm petrel",
  "whitefronted tern",
  "whitehead",
  "whiteheaded petrel",
  "whitenaped petrel",
  "whitewinged black tern",
  "wideawake tern",
  "wideawake",
  "wild duck",
  "wild goose",
  "wild turkey",
  "willock cockatoo",
  "wilson's petrel",
  "wilson's storm petrel",
  "wilsons petrel",
  "wilsons storm petrel",
  "wood pigeon",
  "woodhen",
  "wren",
  "wrybill plover",
  "wrybill",
  "wrybilled plover",
  "yellow bunting",
  "yellow crowned parakeet",
  "yellow eyed penguin",
  "yellow-breasted tit",
  "yellow-breasted tomtit",
  "yellow-crowned parakeet",
  "yellow-crowned penguin",
  "yellow-eyed penguin",
  "yellow-faced cormorant",
  "yellowcrowned parakeet",
  "yelloweyed penguin",
  "yellowhammer",
  "yellowhead"
])