const all_bird_names = new Set([
  "thin-billed prion",
  "hakoko",
  "red billed gull",
  "parasitic jaeger (jaeger is german for hunter)",
  "new zealand grebe",
  "slenderbilled prion",
  "pangurunguru",
  "white-winged tern",
  "mute swan",
  "jackbird",
  "tchaik",
  "titiporangi",
  "yellow bunting",
  "pied oystercatcher",
  "spotted dove",
  "new zealand bellbird",
  "kuihi",
  "australian gannet",
  "bullers mollymawk",
  "white-winged black tern",
  "karoro",
  "richdale's diving petrel",
  "tawake",
  "pakara",
  "putangitangi",
  "spoony",
  "grey warbler",
  "oystercatcher",
  "tui",
  "mohua",
  "blue petrel",
  "white-headed stilt",
  "parara",
  "ngutuparore",
  "kuia",
  "rose cockatoo",
  "yellow-faced cormorant",
  "common skylark",
  "australasian harrier",
  "bar tailed godwit",
  "white-capped albatross",
  "salvins prion",
  "myna",
  "silver-eye",
  "matuku moana",
  "chukar",
  "matuitui",
  "antarctic prion",
  "chatham petrel",
  "white-faced storm petrel",
  "bush falcon",
  "eurasian coot",
  "chinese dove",
  "rose-breasted cockatoo",
  "p\u012bwauwau",
  "purple gallinule",
  "macquarie island cormorant",
  "turnstone",
  "grey teal",
  "south georgian diving petrel",
  "rako",
  "pied tomtit",
  "cape hen",
  "crimson rosella",
  "utick",
  "chaffinch",
  "diving petrel",
  "eastern great egret",
  "white-winged petrel",
  "willock cockatoo",
  "huahou",
  "rock pigeon",
  "parkinson's petrel",
  "campbell albatross",
  "tuanui",
  "cook strait cormorant",
  "k\u0101k\u0101",
  "kakaruai",
  "new zealand rock wren",
  "black robin",
  "gray warbler",
  "spotted shag",
  "great egret",
  "makipai",
  "p\u014dpokatea",
  "rowi",
  "foveaux shag",
  "sulphur crested cockatoo",
  "t\u012brairaka",
  "new zealand falcon",
  "green finch",
  "k\u014dka",
  "blue duck",
  "pacific golden plover",
  "south island pied oystercatcher",
  "gray-backed storm petrel",
  "domestic goose",
  "rock wren",
  "forbes's parakeet",
  "eastern rosella",
  "blue mountain duck",
  "pacific albatross",
  "wilsons storm petrel",
  "new zealand robin",
  "warbler",
  "tuturiwhatu-pukunui",
  "buller's albatross",
  "bounty shag",
  "onga",
  "poaka",
  "kawau tikitiki",
  "pig goose",
  "mollyhawk",
  "cirl bunting",
  "cape barren goose",
  "masked lapwing",
  "tarapo",
  "common myna",
  "mottled petrel",
  "korora",
  "new zealand owl",
  "wedge tailed shearwater",
  "sulphurcrested cockatoo",
  "auckland island flightless duck",
  "long-tailed skua",
  "broad-tailed storm petrel",
  "mollymawk",
  "koera",
  "little black shag",
  "bush robin",
  "buff-banded rail",
  "stewart shag",
  "reischek's parakeet",
  "gould's petrel",
  "konini",
  "jesus christ bird",
  "fulmar",
  "fluttering shearwater",
  "silvereye",
  "little spotted kiwi",
  "black fantail",
  "georgian diving petrel",
  "black tit",
  "okarito brown kiwi",
  "grey headed mollymawk",
  "hakoakoa",
  "white-naped petrel",
  "bittern",
  "kakariki",
  "koro\u0101tito",
  "african collared dove",
  "wilsons petrel",
  "toanui",
  "pacific black duck",
  "gray petrel",
  "yellowhead",
  "blue-grey noddy",
  "bounty cormorant",
  "campbell island mollymawk",
  "eastern rockhopper penguin",
  "grey-backed mollymawk",
  "miromiro",
  "j c bird",
  "whalebird",
  "makipae",
  "caspian tern",
  "kaki",
  "new zealand mountain parrot",
  "auckland island teal",
  "hedge accentor",
  "pahirini",
  "southern royal albatross",
  "southern giant petrel",
  "little owl",
  "pomarine jaeger",
  "macquarie shag",
  "wandering albatross",
  "brown duck",
  "campbell island albatross",
  "hokako",
  "black-fronted tern",
  "fairy penguin",
  "pari",
  "blackbacked gull",
  "p\u0101pango",
  "red-crowned parakeet",
  "pycroft's petrel",
  "yellow eyed penguin",
  "eastern golden plover",
  "bush parrot",
  "kaka",
  "common diving petrel",
  "new zealand dabchick",
  "tasman booby",
  "orange-wattled crow",
  "banded rail",
  "p\u0101teke",
  "southern brown kiwi",
  "northern muttonbird",
  "westland petrel",
  "grey petrel",
  "australasian gannet",
  "carunculated shag",
  "antarctic fulmar",
  "t\u014drea",
  "street pigeon",
  "notornis",
  "canada goose",
  "antipodean albatross",
  "raipo",
  "arctic skua",
  "kohoperoa",
  "auckland island shag",
  "pied tit",
  "korimako",
  "crimson parrot",
  "mallard",
  "baillon's crake",
  "redpoll",
  "t\u012bt\u012b wainui",
  "'ula",
  "uniform parakeet",
  "greenie",
  "black bellied storm petrel",
  "bronze shag",
  "p\u0101rera",
  "blight-bird",
  "red necked stint",
  "k\u014dkako",
  "little blue penguin",
  "chatham island warbler",
  "white-eye",
  "black backed gull",
  "masked gannet",
  "sharptailed sandpiper",
  "whimbrel",
  "parera",
  "p\u016bteketeke",
  "white booby",
  "black cormorant",
  "european starling",
  "chatham island snipe",
  "european greenfinch",
  "p\u014dpokotea",
  "new zealand dotterel",
  "quail hawk",
  "forbes parakeet",
  "laughing kookaburra",
  "t\u016bturuatu",
  "subantarctic skua",
  "bosun bird",
  "auckland island rail",
  "malherbe's parakeet",
  "greenfinch",
  "welcome swallow",
  "campbell flightless teal",
  "mioweka",
  "swamphen",
  "pomarine skua",
  "new zealand gerygone",
  "p\u016bkeko",
  "pohowera",
  "tarepo",
  "taiko",
  "reischeks parakeet",
  "mutton bird",
  "kakariwai",
  "kaka-wairiki",
  "gannet",
  "honge",
  "shore dotterel",
  "black winged petrel",
  "chatham island pigeon",
  "t\u0101iko",
  "tete",
  "new zealand shoveler",
  "antipodes red-crowned parakeet",
  "tar\u0101puka",
  "new zealand king shag",
  "kookaburra",
  "mother carey's chicken",
  "wideawake",
  "finsch's oystercatcher",
  "giant petrel",
  "falcon",
  "buller's gull",
  "tirairaka",
  "kuaka",
  "broad billed prion",
  "wrybill",
  "skylark",
  "wax-eye",
  "kaireka",
  "muttonbird",
  "indian peafowl",
  "dove prion",
  "whitecapped albatross",
  "bush hawk",
  "whistling booby",
  "new zealand shore plover",
  "north island kokako",
  "red-necked stint",
  "t\u016b\u012b",
  "kakaruwai",
  "yellowhammer",
  "wild duck",
  "black-tailed petrel",
  "powhaitere",
  "green parakeet",
  "homing pigeon",
  "parekareka",
  "southern crested grebe",
  "warou",
  "new zealand titmouse",
  "black-backed magpie",
  "light-mantled sooty albatross",
  "pycrofts petrel",
  "k\u0101mana",
  "red-billed gull",
  "flightless duck",
  "forbe's parakeet",
  "goulds petrel",
  "wren",
  "banded dotterel",
  "little tern",
  "swallowtail",
  "ruru",
  "cape pigeon",
  "narrowbilled prion",
  "night parrot",
  "european goldfinch",
  "kakapo",
  "papango",
  "short-tailed shearwater",
  "little pied cormorant",
  "great skua",
  "north island saddleback",
  "storm petrel",
  "white-headed petrel",
  "pukeko",
  "paradise duck",
  "whitechinned petrel",
  "brown bittern",
  "white-chinned petrel",
  "thin billed prion",
  "shining bronze-cuckoo",
  "koka",
  "bartailed godwit",
  "german owl",
  "great crested grebe",
  "parson bird",
  "voc",
  "kingfisher",
  "california quail",
  "sooty rail",
  "forbes' parakeet",
  "p\u012bhoihoi",
  "ring dove",
  "toutouwai",
  "black-backed gull",
  "new zealand pigeon",
  "pihoihoi",
  "great cormorant",
  "chatham island cormorant",
  "blue penguin",
  "crook-bill",
  "asiatic whimbrel",
  "grebe",
  "kokopa",
  "blackbird",
  "tarapunga",
  "masked booby",
  "piwakawaka",
  "fleshfooted shearwater",
  "torea tai",
  "rough-faced shag",
  "werewere",
  "sacred kingfisher",
  "english pheasant",
  "campbell teal",
  "salvins mollymawk",
  "northern mutton bird",
  "black-tailed shearwater",
  "kak\u012b\u0101nau",
  "yellow-crowned penguin",
  "wideawake tern",
  "white-backed magpie",
  "broadbilled prion",
  "goldfinch",
  "yellowcrowned parakeet",
  "light mantled sooty albatross",
  "kahawai bird",
  "sharp tailed sandpiper",
  "antarctic tern",
  "hihi",
  "crested penguin",
  "albatross",
  "p\u012bp\u012bwharauroa",
  "snipe (collective name for several forms now recognised as full species)",
  "grey backed storm petrel",
  "black-billed spoonbill",
  "snowy albatross",
  "white heron",
  "m\u0101tuitui",
  "t\u014drea tai",
  "tasmanian mutton bird",
  "matapouri",
  "pipiwharauroa",
  "fiordland crested penguin",
  "lesser knot",
  "wild turkey",
  "tawaki",
  "black noddy",
  "brown skua",
  "egg bird",
  "greenhead",
  "campbell shag",
  "broad-billed prion",
  "kereru",
  "takahikare-moana",
  "eastern reef egret",
  "kahu",
  "roseate cockatoo",
  "dawson's petrel",
  "auckland teal",
  "black shag",
  "feral pigeon",
  "chatham island yellow-crowned parakeet",
  "redbilled gull",
  "new zealand pipit",
  "shoveller",
  "owl",
  "indian myna",
  "common coot",
  "shy albatross",
  "southern skua",
  "tuke",
  "makomako",
  "kak\u012b",
  "brown quail",
  "long-tailed cuckoo",
  "south island robin",
  "grey-backed shearwater",
  "greylag goose",
  "medium-billed prion",
  "bounty island mollymawk",
  "blackbellied storm petrel",
  "gerygone",
  "new zealand crested penguin",
  "blackfronted dotterel",
  "wood pigeon",
  "antipodes parakeet",
  "roa",
  "tufted guineafowl",
  "barbary dove",
  "stinker",
  "blackbilled gull",
  "pipipi",
  "least golden plover",
  "grey duck",
  "diver",
  "roroa",
  "p\u012bpipi",
  "helmeted guineafowl",
  "white-flippered penguin",
  "kotuku",
  "blue crane",
  "peafowl",
  "allied shearwater",
  "matuku",
  "little pied shag",
  "whio",
  "australasian pied stilt",
  "cinereous wattlebird",
  "spur winged plover",
  "mohoua",
  "fernbird",
  "house swallow",
  "rail",
  "spurwinged plover",
  "titmouse",
  "piwauwau",
  "red crowned parakeet",
  "honker",
  "slender-billed prion",
  "toroa",
  "pacific mollymawk",
  "\u014di",
  "australasian bittern",
  "polar skua",
  "kelp gull",
  "pakaha",
  "blue-faced booby",
  "red parrot",
  "white-cheeked rosella",
  "m\u0101t\u0101t\u0101",
  "black billed gull",
  "reef heron",
  "wedgetailed shearwater",
  "mynah",
  "grey gerygone",
  "tasmanian muttonbird",
  "mockie",
  "hedge sparrow",
  "redcrowned parakeet",
  "black-fronted dotterel",
  "gray-faced petrel",
  "petrel",
  "kamana",
  "tarapuka",
  "coot",
  "black stilt",
  "campbell mollymawk",
  "taihoropi (hokianga)",
  "titi wainui",
  "black browed albatross",
  "sharp-tailed sandpiper",
  "h\u0101koakoa",
  "malay spotted dove",
  "ring-necked pheasant",
  "chatham albatross",
  "pearl-necked dove",
  "longtailed cuckoo",
  "snow petrel",
  "grey faced petrel",
  "onge",
  "new zealand tomtit",
  "thinbilled prion",
  "stewart island shag",
  "creeper",
  "chatham island robin",
  "teal",
  "snipe",
  "north island brown kiwi",
  "black fronted dotterel",
  "new zealand pied oystercatcher",
  "campbell island flightless teal",
  "whitefaced heron",
  "peihana",
  "takahikare",
  "erectcrested penguin",
  "koror\u0101",
  "dove petrel",
  "piropiro",
  "totorore",
  "snares island penguin",
  "pitt island cormorant",
  "grey fantail",
  "new zealand creeper",
  "common blackbird",
  "t\u016bturiwhatu",
  "soft-plumaged petrel",
  "chatham island petrel",
  "shy mollymawk",
  "australian coot",
  "white-capped mollymawk",
  "salvin's mollymawk",
  "black-billed tern",
  "kiwi pukupuku",
  "torea pango",
  "stewart cormorant",
  "teetotum",
  "yellow-eyed penguin",
  "laughing-jackass",
  "tieke",
  "thick-billed penguin",
  "blue-footed petrel",
  "plover",
  "stinkpot",
  "mountain parrot",
  "puweto",
  "antipodes island parakeet",
  "northern giant petrel",
  "blue billy",
  "white fronted tern",
  "bounty mollymawk",
  "bush canary",
  "crowned guineafowl",
  "brown petrel",
  "large pied shag",
  "narrow-billed prion",
  "flesh-footed shearwater",
  "p\u016btangitangi",
  "kawau tui",
  "black oystercatcher",
  "campbell island teal",
  "masked plover",
  "red lowry",
  "buller's mollymawk",
  "little penguin",
  "kokako",
  "long-tailed koel",
  "mackerel gull",
  "white-throated petrel",
  "double-banded plover",
  "chatham island black robin",
  "black swan",
  "grey noddy",
  "grey-faced petrel",
  "koekoea",
  "ranguru",
  "kuku",
  "sulphur-crested cockatoo",
  "k\u014dtare",
  "kerguelen petrel",
  "southern fulmar",
  "house sparrow",
  "karearea",
  "morepork",
  "mallard duck",
  "boomer",
  "pitt island shag",
  "eastern falcon",
  "new zealand storm petrel",
  "kakianau",
  "takah\u0113",
  "chinese pheasant",
  "whiteheaded petrel",
  "westland black petrel",
  "macquarie island shag",
  "white-fronted tern",
  "crested grebe",
  "campbell cormorant",
  "sunday island petrel",
  "bullers albatross",
  "asiatic golden plover",
  "pipit",
  "black-winged petrel",
  "white winged black tern",
  "pied shag",
  "bullers shearwater",
  "kermadec storm petrel",
  "moho perer\u016b",
  "longtailed skua",
  "pale-footed shearwater",
  "harrier",
  "pheasant",
  "whitehead",
  "robin",
  "shag",
  "brown kiwi",
  "redtailed tropicbird",
  "new zealand snipe (collective name for several forms now recognised as full species)",
  "torea",
  "sand plover",
  "little shag",
  "black-bellied storm petrel",
  "gibson's albatross",
  "pitt shag",
  "richard's pipit",
  "whitefaced storm petrel",
  "porete",
  "black-billed gull",
  "t\u0113t\u0113",
  "rifleman",
  "swamp harrier",
  "pateke",
  "t\u0113t\u0113 moroiti",
  "snares island snipe",
  "tiu",
  "stewart island cormorant",
  "parrie",
  "pokotiwha",
  "angel tern",
  "green linnet",
  "long tailed cuckoo",
  "popokatea",
  "softplumaged petrel",
  "black petrel",
  "p\u012bwakawaka",
  "brown-beaked shearwater",
  "weka",
  "fairy tern",
  "knot",
  "yellow crowned parakeet",
  "new zealand shearwater",
  "white-faced heron",
  "kermadec petrel",
  "white bellied storm petrel",
  "king shag",
  "tara",
  "toroa pango",
  "giant fulmar",
  "fiordland penguin",
  "orangefronted parakeet",
  "white faced storm petrel",
  "sipo",
  "weweia",
  "blue heron",
  "yellow-breasted tit",
  "totokipio",
  "new zealand muttonbird",
  "tete moroiti",
  "taratimoho (waikato)",
  "tarapiroe",
  "north island robin",
  "ko'ae",
  "kotoreke",
  "gray ternlet",
  "koroatito",
  "tauhou",
  "pied cormorant",
  "saddleback",
  "snares penguin",
  "south-west pacific swamphen",
  "pitt cormorant",
  "kerer\u016b",
  "new zealand fantail",
  "k\u0101k\u0101riki",
  "koputu",
  "south island wren",
  "black duck",
  "white capped albatross",
  "grey-backed storm petrel",
  "brown creeper",
  "waxeye",
  "eurasian blackbird",
  "grey-headed mollymawk",
  "new zealand snipe (collective name for several forms now recognised as full species)",
  "cape petrel",
  "forster's shearwater",
  "white chinned petrel",
  "northern royal albatross",
  "black-fronted plover",
  "soft plumaged petrel",
  "paradise shelduck",
  "australasian swamphen",
  "song thrush",
  "australasian shoveler",
  "reoreo",
  "t\u0101kupu",
  "otago shag",
  "peale's petrel",
  "toroa-a-ruru",
  "k\u014dtuku",
  "takahe",
  "shore plover",
  "galah",
  "erect-crested penguin",
  "antarctic skua",
  "matuku-h\u016brepo",
  "love tern",
  "white noddy",
  "red tailed tropicbird",
  "huttons shearwater",
  "english sparrow",
  "campbell island cormorant",
  "k\u0101hu",
  "greyheaded albatross",
  "kawau paka",
  "chatham island mollymawk",
  "kotuku ngutupapa",
  "red-tailed tropicbird",
  "campbell black-browed albatross",
  "chatham shag",
  "new zealand plover",
  "common redpoll",
  "subantarctic snipe",
  "magenta petrel",
  "marlborough sounds shag",
  "putoto",
  "little shearwater",
  "t\u012beke",
  "long-tailed jaeger",
  "domestic pigeon",
  "ngirungiru",
  "fulmar prion",
  "white faced heron",
  "tarapirohe",
  "kakariki karaka",
  "brown teal",
  "red knot",
  "lesser broad-billed prion",
  "black-winged stilt",
  "black burrower",
  "blackwinged petrel",
  "new zealand king cormorant",
  "k\u014dtuku ngutupapa",
  "wedge-tailed muttonbird",
  "bell bird",
  "cattle egret",
  "whitefronted tern",
  "tara iti",
  "kea",
  "flesh footed shearwater",
  "titi",
  "silver gull",
  "spotted turtle-dove",
  "rufous-necked stint",
  "blackbrowed mollymawk",
  "whitebellied storm petrel",
  "sparrow hawk",
  "dunnock",
  "parea",
  "arctic tern",
  "tomtit",
  "dominican gull",
  "mountain lowry",
  "black tomtit",
  "pacific gannet",
  "white-throated shag",
  "wrybilled plover",
  "shorttailed shearwater",
  "whitecapped mollymawk",
  "wrybill plover",
  "k\u014dk\u014d",
  "magpie",
  "peacock",
  "gray noddy",
  "manu pango",
  "eurasian skylark",
  "bounty island shag",
  "harrier hawk",
  "rook",
  "south island kokako",
  "royal albatross",
  "eastern turnstone",
  "p\u0101ngurunguru",
  "tuturiwhatu",
  "whale bird",
  "kawau",
  "k\u0101k\u0101po",
  "chatham island albatross",
  "shoemaker",
  "black teal",
  "chatham gerygone",
  "macquarie cormorant",
  "koko",
  "salvins albatross",
  "barwit",
  "matata",
  "kawariki",
  "great white egret",
  "slender-billed fulmar",
  "tokoeka",
  "takupu",
  "chatham island oystercatcher",
  "quail",
  "jackie (chathams)",
  "kawkaw",
  "white cockatoo",
  "wilson's storm petrel",
  "auckland island snipe",
  "peahen",
  "grey headed albatross",
  "t\u012btitipounamu",
  "white-necked petrel",
  "buller's shearwater",
  "orange fronted parakeet",
  "subantarctic little shearwater",
  "hoihoi",
  "tuturuatu",
  "owl-parrot",
  "fairy prion",
  "black-capped petrel",
  "brown parrot",
  "wilson's petrel",
  "australasian crested grebe",
  "t\u0101koketai",
  "skua",
  "rock dove",
  "white naped petrel",
  "chukar partridge",
  "great spotted kiwi",
  "wild goose",
  "woodhen",
  "stitchbird",
  "bar-tailed godwit",
  "new zealand scaup",
  "plumed quail",
  "rednecked stint",
  "wedge-tailed shearwater",
  "hawk",
  "kukupa",
  "native pigeon",
  "honga",
  "southern black-backed gull",
  "new caledonian petrel",
  "t\u012bt\u012b",
  "common chaffinch",
  "white-winged fulmar",
  "purple swamphen",
  "greybacked storm petrel",
  "starling",
  "feral turkey",
  "cook's petrel",
  "parar\u0101",
  "popokotea",
  "chukor",
  "pook",
  "south island takahe",
  "grey-headed albatross",
  "black browed mollymawk",
  "victoria penguin",
  "sea-swallow",
  "blue shag (southern subspecies)",
  "pakah\u0101",
  "k\u0101k\u0101riki karaka",
  "chatham mollymawk",
  "little cormorant",
  "royal spoonbill",
  "kata tei",
  "nelly",
  "k\u0101rearea",
  "blue-billy",
  "pediunker",
  "white-bellied storm petrel",
  "large black shag",
  "oi",
  "ngutu pare",
  "spoonie",
  "korure",
  "mcpherson quail",
  "thrush",
  "kotare",
  "common starling",
  "shining cuckoo",
  "seagull",
  "akiaki",
  "tar\u0101punga",
  "t\u014drea pango",
  "yellow-breasted tomtit",
  "chatham island taiko",
  "scaup",
  "great white heron",
  "orange-fronted parakeet",
  "new zealand kingfisher",
  "sooty tern",
  "kuruwhengi",
  "grey ternlet",
  "taranui",
  "kuera",
  "northern mallard",
  "caledonian petrel",
  "american whimbrel",
  "dotterel",
  "australian magpie",
  "crow",
  "salvin's prion",
  "t\u0101kapu",
  "koitareke",
  "crozet island prion",
  "erect crested penguin",
  "gray\u2019s shag",
  "dabchick",
  "rainbird",
  "cormorant",
  "flightless teal",
  "whitenaped petrel",
  "mourningbird",
  "flutterer",
  "spur-wing",
  "koekoe\u0101",
  "graylag goose",
  "snares snipe",
  "feral goose",
  "blue-gray noddy",
  "silver-grey fulmar",
  "ruddy turnstone",
  "blackfronted tern",
  "shearwater",
  "white swan",
  "white headed petrel",
  "sooty shearwater",
  "marsh crake",
  "tiaki",
  "lightmantled sooty albatross",
  "snares crested penguin",
  "glutton",
  "gray teal",
  "greyheaded mollymawk",
  "light-mantled albatross",
  "takapu",
  "chatham island shag",
  "karuhiruhi",
  "wedge-tailed mutton bird",
  "lesser golden plover",
  "racing pigeon",
  "fantail",
  "blue-wattled crow",
  "riroriro",
  "crozet prion",
  "spoonbill",
  "vieillot\u2019s storm petrel",
  "southern falcon",
  "south polar skua",
  "richdale's penguin",
  "boobook",
  "slender billed prion",
  "pintado petrel",
  "pied fantail",
  "common pheasant",
  "gray duck",
  "titipounamu",
  "narrow billed prion",
  "matuku-hurepo",
  "kakaruia",
  "hoiho",
  "short tailed shearwater",
  "whitewinged black tern",
  "mccormick's skua",
  "south island saddleback",
  "variable oystercatcher",
  "tutukiwi",
  "sooty-capped petrel",
  "black fronted tern",
  "hutton's shearwater",
  "greyfaced petrel",
  "campbell island shag",
  "bellbird",
  "p\u016bweto",
  "frigate petrel",
  "australian brown quail",
  "salvin's albatross",
  "great-winged petrel",
  "white tern",
  "sea vulture",
  "red-breasted dotterel",
  "cooks petrel",
  "red-headed parakeet",
  "k\u0101ruhiruhi",
  "white-capped noddy",
  "yellow-crowned parakeet",
  "campbell black-browed mollymawk",
  "chukor partridge",
  "king cormorant",
  "shoveler",
  "pied stilt",
  "white capped mollymawk",
  "spur-winged plover",
  "amokura",
  "bounty island cormorant",
  "long tailed skua",
  "african ring-necked dove",
  "pigeon",
  "little black cormorant",
  "southern great skua",
  "maui-potiki",
  "laceneck dove",
  "kawau t\u016b\u012b",
  "puteketeke",
  "yelloweyed penguin",
  "parry",
  "ringed turtle dove",
  "blackbrowed albatross",
  "mountain duck",
  "spotless crake"
])